### ISSUE TITLE
Our Motto

### ISSUE THREAD

**Issue by JessiPal** [OpenGenus/Find.the.Lost#1]
We aim to be the group of coders who would help the people in need. In short, we are the "Anonymous" of the world of open source contributions.

"We do not forget. We do not give up. We can do it. We will do it"

**Comment by JessiPal** [comment]
@kilfu0701 @MichalPaszkiewicz @hashimshafiq Why don't you make your membership public? We all are equal and we are the part of this team from Google, Japan for One Direction team.

**Comment by hashimshafiq** [comment]
Doing it :)

**Comment by MichalPaszkiewicz** [comment]
Done!

**Comment by JessiPal** [comment]
Great to have you all on board :smile:

**Comment by hashimshafiq** [comment]
Done !
Thanks @JessiPal

**Comment by catom** [comment]
Best wish to your group  -.- ! @JessiPal
