### ISSUE TITLE
Welcoming (19/04/2016)

### ISSUE THREAD

**Issue by JessiPal** [OpenGenus/Find.the.Lost#2]
@brunocasanova @datudou @jaimejhonle @KarimGabr @MauricioTorre @peterdotjs @recepcoban @tacheshun @wulfgarpro 
:walking: 
I warmly welcome you all on board. Soon we will be contributing on real time needy projects at our wish. It is good to see you all joining hands to use our coding powers to achieve something extraordinary. Feel free to keep your membership public as this is an open group for good. :smiley: 
We are the "Anonymous" of open source contributions.

Comment to introduce yourself to everyone on board.

"We do not forget. We do not give up. We can do it. We will do it"

**Comment by wulfgarpro** [comment]
Hi Jess,

I've taken a look at the NGO website linked to on your github organisation
page.  It interests me, but I'd like some more information of your vision
and possible project work going into the future?

Jim

On Wed, Apr 20, 2016 at 2:56 AM, Jessica Pal notifications@github.com
wrote:

> @brunocasanova https://github.com/brunocasanova @datudou
> https://github.com/datudou @jaimejhonle https://github.com/jaimejhonle
> @KarimGabr https://github.com/KarimGabr @MauricioTorre
> https://github.com/MauricioTorre @peterdotjs
> https://github.com/peterdotjs @recepcoban
> https://github.com/recepcoban @tacheshun https://github.com/tacheshun
> @wulfgarpro https://github.com/wulfgarpro
> [image: :walking:]
> I warmly welcome you all on board. Soon we will be contributing on real
> time needy projects at our wish. It is good to see you all joining hands to
> use our coding powers to achieve something extraordinary. Feel free to keep
> your membership public as this is an open group for good. [image:
> :smiley:]
> We are the "Anonymous" of open source contributions.
> 
> "We do not forget. We do not give up. We can do it. We will do it"
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/OpenGenus/Find.the.Lost/issues/2

## 

James

GPG: B714 260C 4F39 3522 0D55  A13D 89AC 3DE2 _550A 2F53_

**Comment by JessiPal** [comment]
We are all in a team. Here we value vision of all members matter.
Our aim is to help everyone with the technology we can build. Whether small or big, we can make a difference. We hope to become the bridge between NGOs and the Software world. Already, we had a warm response but we have a long way to go.
I have in mind some projects that would prove to be significant. Though, we must decide upon it all together. Remember we have to build the largest group of such kind of technological help.
We have partnered with some NGOs and technical organizations in Japan but we have to enforce the importance of the difference we can make with our code rather than financial contributions. There had been a stire here that Google is interested by our initiative.
One problem we are facing is communication in Github. Do you have any suggestion which would help communication between all team members ?
Already there are platforms that provide significant knowledge for free but the problem we are facing is internet access and no platform for readily supplying employment. We cannot employ as we are an open group but every can accept anyone in our group. We aim to build a universal platform to impart live technical knowledge(such as instant live guidance for surgery which other platforms lack) like live chat, remove the concept of governments but safely establish a common planet of collaboration,  network for transferring required stuffs and much more.
If successful, we can solve the internet problem by partnering with Facebook. Let see where we can go.
Provide your suggestions and views. :smiley:

**Comment by wulfgarpro** [comment]
> One problem we are facing is communication in Github. Do you have any
> suggestion which would help communication between all team members ?

Slack https://slack.com/

I'm interested, but we need concrete problems to solve rather than the
notion of possible projects.  Maybe put up a problem that can be solved and
people can start discussing solutions.

On Sat, Apr 23, 2016 at 10:25 PM, Jessica Pal notifications@github.com
wrote:

> We are all in a team. Here we value vision of all members matter.
> Our aim is to help everyone with the technology we can build. Whether
> small or big, we can make a difference. We hope to become the bridge
> between NGOs and the Software world. Already, we had a warm response but we
> have a long way to go.
> I have in mind some projects that would prove to be significant. Though,
> we must decide upon it all together. Remember we have to build the largest
> group of such kind of technological help.
> We have partnered with some NGOs and technical organizations in Japan but
> we have to enforce the importance of the difference we can make with our
> code rather than financial contributions. There had been a stire here that
> Google is interested by our initiative.
> One problem we are facing is communication in Github. Do you have any
> suggestion which would help communication between all team members ?
> Already there are platforms that provide significant knowledge for free
> but the problem we are facing is internet access and no platform for
> readily supplying employment. We cannot employ as we are an open group but
> every can accept anyone in our group. We aim to build a universal platform
> to impart technical knowledge(such as instant live guidance for surgery
> which other platforms lack), remove the concept of governments but safely
> establish a common planet of collaboration, network for transferring
> required stuffs and much more.
> If successful, we can solve the internet problem by partnering with
> Facebook. Let see where we can go.
> Provide your suggestions and views. [image: :smiley:]
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/OpenGenus/Find.the.Lost/issues/2#issuecomment-213732371

## 

James

GPG: B714 260C 4F39 3522 0D55  A13D 89AC 3DE2 _550A 2F53_

**Comment by sideffect0** [comment]
These Repo title seems a catch, any one here help me, how i can contribute to this project, am interested on this movement NGO :)

**Comment by JessiPal** [comment]
Hello @sideffect0 I have send you an invite.
Everyone here is very enthusiastic and as this is the beginning, things are moving slow but soon may be in a month, we all would be assigned part of work for accomplishing our mission. Join the group and call new members. We will soon be solving real life problems and changing the face of technology.
Looking forward to having you on board.

**Comment by availchet** [comment]
What all have you guys done yet? And how can i contribute?
